name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run type-check

      - name: Run Tests
        run: npm test -- --runInBand

      - name: Build (renderer + electron)
        run: npm run build

      - name: Package MSIX (no publish)
        run: npm run build:msix

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: msix-package
          path: dist/build/*.msix
          if-no-files-found: warn

      - name: Upload Logs (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            dist/build
            npm-debug.log*
